### ISSUE TITLE
Add support for aarch64-apple-darwin

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-about#137]
Did a quick test build for it and seems the main issue is or rpmalloc crate which is lacking support (https://github.com/EmbarkStudios/rpmalloc-rs/issues/11). We could for now disable the custom global allocator for now for this target

**Comment by badboy** [comment]
Just ran into this. Would you accept a PR that disables that dependency on aarch64-apple-darwin? I can prepare one tomorrow.

**Comment by repi** [comment]
We probably should just switch to the [`mimalloc`](https://crates.io/crates/mimalloc) crate which we already use on on all targets (including `aarch64-apple-darwin`) in other projects.

A PR with that would be most welcome!

**Comment by badboy** [comment]
Oh, even easier. I can do that too!

**Comment by badboy** [comment]
Question though: why does this crate even _need_ a custom allocator? Is it that allocation-heavy that it really benefits much from a non-system one?

**Comment by Jake-Shadle** [comment]
I think it was primarily to speed up `x86_64-unknown-linux-musl` since its allocator was pretty terrible wrt parallelization and it's easier to just use the same allocator for all targets (until we hit issues like this).

**Comment by repi** [comment]
Yes I think that was the original issue, and maybe also that on Windows it was really slow with the system allocator that made an actual impact.
