### ISSUE TITLE
Ignore transitive dependencies via config flag

### ISSUE THREAD

**Issue by haraldreingruber-dedalus** [EmbarkStudios/cargo-about#144]
For our about box we would just list the direct dependencies.
A config flag for ignoring transitive dependencies would be awesome!

Thanks a lot for sharing this really helpful tool 🙏

**Comment by Jake-Shadle** [comment]
Seems reasonable!

**Comment by haraldreingruber** [comment]
@Jake-Shadle we might look into working on a PR. I had a quick look into the repo, I guess such an option has to be passed in one way or another to the krates library, where the dependency graph is resolved?

Could you help me to find a potential starting point where the functionality would need to be implemented?
I had a look at the krates::builder module, but I did not yet spot the part resolving the transitive dependencies.

**Comment by Jake-Shadle** [comment]
I think this would be the primary [location](https://github.com/EmbarkStudios/krates/blob/a0261370ad5e717b4c3b805f976905ebf8e5ee34/src/builder.rs#L673-L683) to change. I think just changing the pid_stack to be a tuple of the package id as well as the depth of the dependency would mean you could just increment the depth when new packages are pushed onto the stack, and then if a depth limit is specified on the builder, just ignoring dependencies at that depth or lower.

**Comment by Jake-Shadle** [comment]
Closed by #188
