### ISSUE TITLE
Missing .vscode/settings.json

### ISSUE THREAD

**Issue by MaulingMonkey** [EmbarkStudios/cargo-about#147]
**Describe the bug**

[Embark Guidelines](https://github.com/EmbarkStudios/rust-ecosystem/blob/main/guidelines.md#development-environments) state:

> As we want to [run rustfmt on save](https://github.com/EmbarkStudios/rust-ecosystem/blob/main/guidelines.md#001---run-rustfmt-on-save), all of our repos should have a `.vscode/settings.json` with:
> ```json
> {
>     "editor.formatOnSave": true,
> }
> ```

But this file is missing from cargo-about.

**Comment by Jake-Shadle** [comment]
We don't expect everyone to use VSCode, this is just a local setup suggestion to improve your own workflow, all of our repos require the rustfmt check passes in CI regardless.
