### ISSUE TITLE
Add a `--workspace` flag

### ISSUE THREAD

**Issue by MaulingMonkey** [EmbarkStudios/cargo-about#151]
**Is your feature request related to a problem? Please describe.**
I'm publishing an about page for someone else's repository - <https://github.com/Syn-Nine/rust-mini-games> - which I've added a workspace to in my fork.  Individual crates don't specify package license metadata, but there is a single `LICENSE-MIT` in the root.  To support referencing the original license file, I'd like to make a stub package in the root of the repository - in the same directory as the root of my workspace - that serves no other purpouse than to reference the license file.

However, by doing this, `cargo about` no longer generates license metadata for the entire workspace - but only the empty stub package.

**Describe the solution you'd like**
Adding a `--workspace` flag to `cargo about generate` could allow `cargo about` to generate license metadata for the entire workspace, regardless of subdirectory and the presence of a root package or not.

**Describe alternatives you've considered**
* Making 6+ copies of `LICENSE-MIT`s, one for each package, and modifying said individual packages to reference them.
* Replacing individual package tomls with a single package and workspace.
* Making 1 copy of `LICENSE-MIT` in another subdirectory, and putting the package there.
* Inlining `LICENSE-MIT` into my `about.hbs` (my current solution)
* Making the stub package depend on all the other packages (they're all bin-only though)
* Proposing a mechanism like `[[DEPENDENCY.additional]]`, only for ambient dependencies outside the scope of any individual crate.

Most of these all involve more awkward/invasive changes - I'm trying to keep my fork as close to the (relatively unresponsive) upstream as possible.

**Comment by Jake-Shadle** [comment]
Seems reasonable.
