### ISSUE TITLE
`cargo about generate <templates>` documentation is cut off mid-sentence

### ISSUE THREAD

**Issue by sjohannes** [EmbarkStudios/cargo-about#161]
`cargo about generate --help` ends with an incomplete sentence

```
ARGS:
    <templates>    The template or template directory to use. Must either be a .hbs or have at least
```

due to

https://github.com/EmbarkStudios/cargo-about/blob/308e3e040a4bb8b23b8fac14aa4bee2355fbf735/src/cargo-about/generate.rs#L22-L25

(Also, it's currently unclear what passing a directory does exactly, so perhaps that could be filled in as well.)

**Comment by Jake-Shadle** [comment]
Oops, this was fixed in #169
