### ISSUE TITLE
Output using "ring" crate is corrupted

### ISSUE THREAD

**Issue by jeff-hiner** [EmbarkStudios/cargo-about#167]
**Describe the bug**
License text for `ring` (OpenSSL) is corrupted

**To Reproduce**
1. Create a new project with `cargo new`
2. Add `ring = "0.16"` to Cargo.toml dependencies
3. Create required files with `cargo about init`, edit about.toml and add missing licenses (ISC and OpenSSL)
4. Generate license docs with `cargo about generate`

**Expected behavior**
Output contains the text of LICENSE from ring, without random C code like this:
```
#include &quot;internal.h&quot;
#include &quot;../../internal.h&quot;

#include &quot;../../limbs/limbs.h&quot;
#include &quot;../../limbs/limbs.inl&quot;

OPENSSL_STATIC_ASSERT(BN_MONT_CTX_N0_LIMBS &#x3D;&#x3D; 1 || BN_MONT_CTX_N0_LIMBS &#x3D;&#x3D; 2,
  &quot;BN_MONT_CTX_N0_LIMBS value is invalid&quot;);
OPENSSL_STATIC_ASSERT(
  sizeof(BN_ULONG) * BN_MONT_CTX_N0_LIMBS &#x3D;&#x3D; sizeof(uint64_t),
  &quot;uint64_t is insufficient precision for n0&quot;);

int GFp_bn_from_montgomery_in_place(BN_ULONG r[], size_t num_r, BN_ULONG a[],
                                    size_t num_a, const BN_ULONG n[],
                                    size_t num_n,
                                    const BN_ULONG n0_[BN_MONT_CTX_N0_LIMBS]) {

```

**Device:**
 - OS: Debian stable
 - Version 0.3.0

**Comment by Jake-Shadle** [comment]
I'm going to close this as cargo-about now includes a [workaround](https://embarkstudios.github.io/cargo-about/cli/generate/workarounds.html#ring) for ring and only includes license text from the actual LICENSE file in ring.
