### ISSUE TITLE
Build error on 0.4.2 release

### ISSUE THREAD

**Issue by senden9** [EmbarkStudios/cargo-about#175]
**Describe the bug**
The latest release (0.4.2) fails to build on my machine. Error:
```
error[E0599]: no method named `compat` found for struct `anyhow::Error` in the current scope
  --> /home/stefano/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-about-0.4.2/src/licenses.rs:21:24
   |
21 |         .map_err(|e| e.compat())
   |                        ^^^^^^ method not found in `anyhow::Error`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `cargo-about` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-about v0.4.2`, intermediate artifacts can be found at `/tmp/cargo-installGSR9B8`
```

**To Reproduce**
Try to install the latest `cargo-about` release with `cargo install --version "=0.4.2" cargo-about`

**Expected behavior**
`cargo-about` can be compiled successful.

**Device:**
 - OS: Ubuntu 20.04.3 LTS
 - Rust Compiler: `rustc 1.56.1 (59eed8a2a 2021-11-01)`

**Additional Infos:**
If I compile the latest version of this git repo (0c74659e7e24f3a894cdb3a6e7dacfd2ea8c6b48) `cargo build` as well as `cargo build --release` can compile. Maybe the version on crates.io is different :thinking: .

**Comment by senden9** [comment]
Verbose build log created with `cargo install --version "=0.4.2" --verbose cargo-about`:
[cargo-about-build.txt](https://github.com/EmbarkStudios/cargo-about/files/7578987/cargo-about-build.txt)

**Comment by Jake-Shadle** [comment]
No, it's just using a different version of anyhow, you can use `--locked` to use the exact Cargo.lock that was published (cargo install doesn't do this which is footgun). I will also publish a fix shortly.

**Comment by Jake-Shadle** [comment]
Sorry I lied, not anyhow, this was due to a bump in `askalono` which replaced failure with anyhow.

**Comment by senden9** [comment]
Ah, I didn't know that `cargo install` did not use the lock-file by default. This explains why a local `cargo build` is just fine.
Thank you for the explanation and the quick release of a "fixed" version @Jake-Shadle!
