### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-about#18]
We don't have any tests at all for this crate right now, which is not great as makes it more difficult to take in contributions and to make sure the crate works when we update dependencies or does changes to it.

Think a good start would be to add a small integration test where we run cargo about on a small checked-in test crate that has 1 dependency with 2 different licenses we pick and with a specific template to verify the output is the same (which we can check in).

And would always be good with unit tests for specific features and functionality, more scalable than having integration tests. 

Would be hard to manually find and detect if bugs creep into this and we start missing licenses and attribution for certain crates, hence having tests will be extra important.

**Comment by Schoonology** [comment]
I'd be happy to try this, and can (feel like I _should_) contribute in the following stages:

- A [bats](https://github.com/bats-core/bats-core)-based end-to-end test that verifies the behaviour at the outermost level.
- A series of unit tests that verify module boundaries. The place to start seems like `src/licenses/mod.rs`.

Would this contribution be helpful? How do you feel about this approach?

**Comment by Jake-Shadle** [comment]
Cool that you want to take a look at this!

I would say we wouldn't want the `bats` option at all, if you wanted to add "UX" tests you could do something like what is suggested [here](https://rust-cli.github.io/book/tutorial/testing.html#testing-cli-applications-by-running-them)
