### ISSUE TITLE
`private = { ignore = true }` is rejected

### ISSUE THREAD

**Issue by Geobert** [EmbarkStudios/cargo-about#192]
**Describe the bug**
Following https://embarkstudios.github.io/cargo-about/cli/generate/config.html#the-ignore-field I put
```
[licenses]
private = { ignore = true }
``` 

into my about.toml (at the end of the file) and it is rejected when running
`cargo about generate about.hbs`

**Expected behavior**
should accept `private` field as mentioned in the book

**Device:**
 - OS: Ubuntu in WSL
 - Version cargo-about 0.5.1

**Comment by Jake-Shadle** [comment]
I've clarified the docs in https://github.com/EmbarkStudios/cargo-about/commit/b571fa0d86bcf9ff87d08ab66c99a4316fbcd898, the `[licenses]` key should not be there, and private must come before any crate configurations.

**Comment by Geobert** [comment]
That did it, thanks!
