### ISSUE TITLE
json ouput

### ISSUE THREAD

**Issue by lizelive** [EmbarkStudios/cargo-about#196]
**Is your feature request related to a problem? Please describe.**
i want to run the template at runtime

**Describe the solution you'd like**
either add a flag `--no-template`, or make it default cargo about > about.json

**Describe alternatives you've considered**
adding `json_to_str` handlebar helper

**Additional context**
nope

**Comment by prestomation** [comment]
I found a workaround to this was a template where the entire content is `{{{json this}}}`
