### ISSUE TITLE
Something isn't handling encoding correctly

### ISSUE THREAD

**Issue by ilyvion** [EmbarkStudios/cargo-about#198]
Running `cargo about generate about.hbs > license.html` on my project, which has a dependency on `is_ci 1.1.1` generates the following output in the HTML:
```
                <pre class="license-text">The ISC License

Copyright (c) Kat March├ín and other contributors.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED &quot;AS IS&quot; AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.Apache License
</pre>
```
the problem (in case it's not obvious) is that this says `March├ín`, while [the original](https://github.com/zkat/is_ci/blob/main/LICENSE) says `Marchán`:
```
The ISC License

Copyright (c) Kat Marchán and other contributors.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.Apache License
```
(I've gone and checked that the file (presumably) used as input (i.e. `~/.cargo/registry/src/github.com-1ecc6299db9ec823/is_ci-1.1.1/LICENSE` does indeed have `Marchán` as such when read as UTF-8.

**Device:**
 - OS: Windows 10
 - Version 0.5.1

**Comment by ShouvikGhosh2048** [comment]
```
fn main() {
    println!("á");
}
```
If you run `cargo run --release > new.txt`
- Powershell writes ├í to the file.
- Cmd writes á to the file.

**Comment by alexschrod** [comment]
Ah yeah, there does seem to be an issue with Powershell and encoding.
That's not great. I guess that's the problem then. I was aware that it
saved as UTF-16LE, but not that it also mangled the input UTF-8 in the
process. It's weird how it can display the output from the program just
fine, but if you try to redirect it, well, time to mangle!

**Comment by Jake-Shadle** [comment]
Ahh ok, that's indeed unfortunate. I would accept a PR that adds either a check for if the terminal is powershell and raise an error if stdout is being redirected and point the user to the `-o` flag, or at least a warning in the documention or Cli help
