### ISSUE TITLE
Return error code in case of warnings

### ISSUE THREAD

**Issue by Niederb** [EmbarkStudios/cargo-about#203]
**Is your feature request related to a problem? Please describe.**
For our CI I would like the execution of `cargo-about` to return an error code if there are any warnings (e.g. `crate XY doesn`t have a license field`) such that our build pipeline would fail if there are any warnings. Currently it is easy to overlook these warnings. 

**Describe the solution you'd like**
It would be nice to have a config flag like `fail-on-warning` to support this use case.

**Describe alternatives you've considered**
We could also check/parse the output of `cargo-about` but I would prefer to just return an error code.

**Comment by Jake-Shadle** [comment]
Resolved by #213
