### ISSUE TITLE
Install requires a Rust version greater than the MSRV

### ISSUE THREAD

**Issue by kimono-koans** [EmbarkStudios/cargo-about#209]
**Describe the bug**
MSRV for this project is 1.56.1.  When using the supplied installation instructions, the project refuses to compile without Rust version 1.65.0:
```bash
~ cargo install --locked cargo-about
    Updating crates.io index
  Installing cargo-about v0.5.2
error: failed to compile `cargo-about v0.5.2`, intermediate artifacts can be found at `/tmp/cargo-installVjv2oi`

Caused by:
  package `cargo-about v0.5.2` cannot be built because it requires rustc 1.65.0 or newer, while the currently active rustc version is 1.61.0
```

**To Reproduce**
1. Execute `cargo install --locked cargo-about` on Linux or MacOS

**Expected behavior**
Expect the project to install with either Rust 1.61 on Linux or 1.64 on MacOS.

**Comment by Jake-Shadle** [comment]
The MSRV was incorrect in the README, it's been updated.
