### ISSUE TITLE
Standard library license isn't included

### ISSUE THREAD

**Issue by solomatov** [EmbarkStudios/cargo-about#212]
**Describe the bug**
Output generated by the library doesn't contain license of the rust standard library. It's required, see the discussion here: https://internals.rust-lang.org/t/does-the-standard-library-have-linking-exceptions-to-their-licensing/11377/17

**To Reproduce**
- Create empty project
- Generate config
- Generate license.html
- Observer that it doesn't have anything related to the std lib

**Expected behavior**
- Standard library licensing information should be included

**Screenshots**

**Device:**
- Any OS, any device

**Additional context**
- https://internals.rust-lang.org/t/does-the-standard-library-have-linking-exceptions-to-their-licensing/11377/17
- https://github.com/rust-lang/rust/issues/67014

**Comment by Jake-Shadle** [comment]
Duplicated #16
