### ISSUE TITLE
Docs incorrectly list override-git-commit instead of override_git_commit

### ISSUE THREAD

**Issue by akonradi-signal** [EmbarkStudios/cargo-about#239]
**Describe the bug**
The documentation says that `override-git-commit: [hash]` can be used in about.toml to override the commit used to find the license file. That's not correct; the field is called `[override_git_commit](https://github.com/EmbarkStudios/cargo-about/blob/a4296450258de52c728ddfb33fd8769be91d31e7/src/licenses/config.rs#L151).

**Comment by Jake-Shadle** [comment]
The docs are correct, the code was not, the field is now renamed to be what it was supposed to be, thanks for raising this issue.
