### ISSUE TITLE
Add --offline capability

### ISSUE THREAD

**Issue by matthiasbeyer** [EmbarkStudios/cargo-about#246]
I want to run the tool without internet access (inside a nix build).
But right now it does not seem to be possible.

Could a feature for this be added?

**Comment by apljungquist** [comment]
I too would like this (I actually want reproducible results, but the inconsistent results seem to go away when I set `no-clearly-defined`, so I'm guessing an offline mode would help me as well).

**Comment by apljungquist** [comment]
Nice, thanks @Jake-Shadle!
