### ISSUE TITLE
Missing license for multi-license dependency

### ISSUE THREAD

**Issue by apanloco** [EmbarkStudios/cargo-about#256]
**Describe the bug**

When generating license information with cargo about for the `encoding_rs` dependency, with license `(Apache-2.0 OR MIT) AND BSD-3-Clause`, there is no trace of the MIT license.

**To Reproduce**

1. cargo new abouttest && cd abouttest
2. cargo add encoding_rs
3. cargo about init
4. add BSD-3-Clause to accepted licenses
5. cargo about generate about.hbs > output.html

**Expected behavior**
There should be an MIT license in the full text licenses in output.html, but there's only Apache and BSD.

**Device:**
Version 0.6.4 of cargo about

**Comment by Jake-Shadle** [comment]
It's only required to satisfy one side of an `OR`, and presumably you have Apache-2.0 before MIT in your allow list, thus it uses apache-2.0 and ignores MIT.

**Comment by apanloco** [comment]
Aha, I see. Thanks for the answer!
