### ISSUE TITLE
Add flag to ignore dev and/or build dependencies

### ISSUE THREAD

**Issue by hardliner66** [EmbarkStudios/cargo-about#27]
If you have build dependencies which uses a non-accepted license, the tool fails and doesn't generate any output.

Currently the only workaround is to manually remove the build depencies before running the tool, which is not viable for usage in a CI workflow.

It would be nice to have some way to configure this. Either with command line flags or inside the about.toml.

**Comment by repi** [comment]
Agreed, have run into this as well wrt to the attribution output, only wanted to show it for the actual dependencies used in our executable, not dev & build dependencies. Should be configurable in `about.toml` as different projects and repos may want to handle it differently. 

Same with `cargo-deny` as well.

**Comment by Jake-Shadle** [comment]
Oops, this was also fixed by #41 :man_facepalming:
