### ISSUE TITLE
Only include dependencies used for specified targets

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/cargo-about#36]
We need to fix so we only include and attribute crates that we actually use for the target platforms we ship on. Right now all dependencies are included even if they are for fairly exotic targets that we do not use nor ship (redox, fuchsia).

Would be good to keep the current behavior and include dependencies from all targets, but add being able to specify which targets to include and filter for, including supporting multiple targets. 
Could have such a config in `about.toml` of supported targets, as Cargo doesn't have it itself anywhere yet (though really should have). But would also be useful to be able to specify target to generate for with a `--target` parameter so one can quickly test a specific target or in CI generate target-specific correct output.

In Rust 1.41 the lockfile should contain the target information also so should then add this support together with the target-filtering in cargo-deny (https://github.com/EmbarkStudios/cargo-deny/issues/63).

**Comment by Jake-Shadle** [comment]
Oops, this was fixed in #41
