### ISSUE TITLE
Allow specifying `generate` output

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/cargo-about#56]
Right now the output generated by the `generate` subcommand gets written directly to stdout, we should also allow specifying an output file, and only use stdout if it's not specified, or is `-`.

**Comment by sjohannes** [comment]
This is fixed by https://github.com/EmbarkStudios/cargo-about/pull/148 and can be closed.

**Comment by Jake-Shadle** [comment]
Yup, oops.
