### ISSUE TITLE
The readme's suggested `cargo about init` seems to be invalid usage.

### ISSUE THREAD

**Issue by Lokathor** [EmbarkStudios/cargo-about#7]
```
D:\dev\learn-opengl>cargo about init
error: Found argument 'init' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-about.exe [OPTIONS] <SUBCOMMAND>

For more information try --help
```
Perhaps the readme is old? or it's for the next version to be published?

**Comment by Lokathor** [comment]
Ah, yes, an install from the git master works!

Perhaps a note should be put in the readme about that until the next version goes out.

**Comment by MaikKlein** [comment]
No version has been released yet. The crate is going the be published soon, sorry for the inconvenience.

**Comment by WildCryptoFox** [comment]
@MaikKlein 0.0.1 has been released and this version is advertised in the README with the crates.io badge.

https://docs.rs/cargo-about/0.0.1/cargo_about/
