### ISSUE TITLE
handlebars processing seems to be swallowing newlines

### ISSUE THREAD

**Issue by jrpascucci** [EmbarkStudios/cargo-about#77]
Version: 0.2.0
```
With newlines in <pre> formatted sections in the hbs, the generated .html has the newlines removed. This is true whether it's static text or {{text}} from a license.

(Happens to be running on windows, but don't see any unix newlines either)

This was not a problem with 1.x.
```

**Comment by jrpascucci** [comment]
I attempted a few things like updating the <meta> tag, to no avail.

**Comment by Jake-Shadle** [comment]
There was a handlebars update in between versions so its possible there was a behavior change/regression. Will take a look when I have a chance.

**Comment by jrpascucci** [comment]
Now I'm looking at it, it's possible this is a user-error and it did have something to do with windows. I'm checking my side further, I'll close if I figure it out, hold off delving deep.

**Comment by jrpascucci** [comment]
Mea culpa, it was a post-processing step on windows. Will close.

**Comment by Jake-Shadle** [comment]
Ahh great, thanks for filing (and closing) anyway!
