### ISSUE TITLE
crates using license-file are considered to have no license set

### ISSUE THREAD

**Issue by WildCryptoFox** [EmbarkStudios/cargo-about#9]
Crates like [fuchsia-cprng](https://docs.rs/fuchsia-cprng) use `license-file = "LICENSE"` instead of `license = "XXX"`.

https://docs.rs/crate/fuchsia-cprng/0.1.1/source/Cargo.toml.orig

```
[WARN] crate 'fuchsia-cprng(0.1.1)' doesn't have a license field
```

**Comment by Jake-Shadle** [comment]
This probably should be an `info` level message instead, the license file is still used later.
